### ISSUE TITLE
Conflicting license information in NOTICE.md file

### ISSUE THREAD

**Issue by kswartz26** [eclipse-ee4j/orb#101]
The notice file currently states the material in this repository is licensed under a choice of EDL 1.0 or EPL v2 with secondary license GPLv2+CPE. However, there is no copy of the EPL license and all of the source code headers specify only EDL 1.0.

I suspect that text was meant to apply generally to all of the ORB content, but it's misleading to have this text in the notice file for this specific repository.

**Comment by waynebeaton** [comment]
The project is, per [board resolution](https://bugs.eclipse.org/bugs/show_bug.cgi?id=534159#c6) (as requested by the contributors) is not the default for EE4J projects. It should be EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH Classpath-exception-2.0. The license file needs to include the EDL.

Further, the source file headers need to be updated to something along the lines of this:

    /********************************************************************************
     * Copyright (c) {date} {owner}[ and others]
     * 
     * This program and the accompanying materials are made available under the
     * terms of the Eclipse Public License v. 2.0 which is available at
     * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
     * v. 1.0 which is available at
     * http://www.eclipse.org/org/documents/edl-v10.php.
     * 
     * This Source Code may also be made available under the following Secondary
     * Licenses when the conditions for such availability set forth in the Eclipse
     * Public License v. 2.0 are satisfied: GNU General Public License v2.0
     * w/Classpath exception which is available at
     * https://www.gnu.org/software/classpath/license.html.
     * 
     * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
     * Classpath-exception-2.0
     ********************************************************************************/

**Comment by smillidge** [comment]
@waynebeaton so we have to update all the source files?

**Comment by waynebeaton** [comment]
Yes. 

There is some help in [Bug 530393](https://bugs.eclipse.org/bugs/show_bug.cgi?id=530393).
