### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown from org.glassfish.rmic.tools.java.ClassPath

### ISSUE THREAD

**Issue by ericvdmaarel** [eclipse-ee4j/orb#105]
The `ClassPath` utility provides a class path representation. It has a constructor that tries to build an array of `ClassPathEntry` elements from a class path string. It allocates an array for which the size is determined by counting the number of `File.pathSeparatorChar`s in the provided class path string. Then it goes on and fills it with elements read from the class path string. Finally it tries to add the `jrt:/` virtual file system. Since this was not anticipated the index for the next array element is larger than the array allows, resulting in an `ArrayIndexOutOfBoundsException` getting thrown.

**Comment by pzygielo** [comment]
With #106 merged, this could be closed I suppose?

**Comment by ericvdmaarel** [comment]
Yep closed it. Thanks for reminding me.
