### ISSUE TITLE
Maven dependencies not able to download in Eclipse

### ISSUE THREAD

**Issue by vishnuprakash9845** [eclipse-ee4j/orb#127]
So in the pom.xml tried to download the Java Client dependency, but getting the below error

Eclipse Version: 2020-09 (4.17.0)
Build Id: 20200910-1200

Can anyone help me on this issue please

Description Resource Path Location Type
Error while downloading 'https://maven.apache.org/xsd/maven-4.0.0.xsd' to /Users/muniswamyv/.lemminx/cache/https/maven.apache.org/xsd/maven-4.0.0.xsd. pom.xml /appiumFramwork line 1 Language Servers
Description Resource Path Location Type
Error while downloading 'https://maven.apache.org/xsd/maven-4.0.0.xsd' to /Users/vishnu/.lemminx/cache/https/maven.apache.org/xsd/maven-4.0.0.xsd. pom.xml /appiumFramwork line 1 Language Servers
Description Resource Path Location Type
Missing artifact io.appium:java-client:jar:7.6.0 pom.xml /appiumFramwork line 1 Maven Dependency Problem
Description Resource Path Location Type
Missing artifact io.appium:java-client:jar:7.6.0 pom.xml /appiumFramwork line 1 Maven Dependency Problem
![image](https://user-images.githubusercontent.com/24207575/146875867-f810c1ce-3df9-4fd1-84ae-6ead826c4617.png)

**Comment by smillidge** [comment]
I don't see that this bug as anything to do with this project?
