### ISSUE TITLE
Support for PFL 5.0.0

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/orb#188]
See https://github.com/eclipse-ee4j/orb-gmbal/issues/32

**Comment by dmatej** [comment]
See https://github.com/eclipse-ee4j/orb/pull/172 , @pzygielo  already watches this :-)

**Comment by dmatej** [comment]
Just for all, I started doing some cleanup for PFL and ORB and I will test it by GlassFish's tests.
