### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/orb#27]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538675

**Comment by vinayvishal** [comment]
The master build job for this project has been successfully created, hence closing this issue.
