### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/orb#28]
This task is for creating a project release CI/CD pipeline. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by vinayvishal** [comment]
Orb master build is done and is working fine. Orb release build is in progress, since its a multi module project, we are in the process of understanding the existing release process post which job needs to be tuned accordingly.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.
