### ISSUE TITLE
javax.rmi package should be exported

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/orb#31]
with corba removal from jdk11, there is currently no clean way to use this implementation on within OSGi framework running on JDK 11. The problem is that package 'javax.rmi' is not exported by glassfish-corba-omgapi, so it is not possible to call 'javax.rmi.PortableRemoteObject.narrow' within OSGi environment when using this library

**Comment by lukasj** [comment]
@m0mus this should be blocking the release... I cannot add it to the board

**Comment by m0mus** [comment]
@lukasj Added to the board

**Comment by vinayvishal** [comment]
Closing this one as PR #43 has been merged.
