### ISSUE TITLE
Warning: Supported source version 'RELEASE_6' from annotation processor 'org.glassfish.corba.annotation.processing.ExceptionWrapperProcessor' less than -source '11'

### ISSUE THREAD

**Issue by ahubold** [eclipse-ee4j/orb#45]
org.glassfish.corba.annotation.processing.ExceptionWrapperProcessor is annotated with `@SupportedSourceVersion(SourceVersion.RELEASE_6)`.

This annotation sets the "the latest source version an annotation processor supports."

As a consequence, there are lots of warnings when the jar is on the compile classpath, because the annotation processor is enabled by default via `META-INF/services/javax.annotation.processing.Processor` 

For example with Java 11:

```
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'org.glassfish.corba.annotation.processing.ExceptionWrapperProcessor' less than -source '11'
```

**Comment by smillidge** [comment]
Fixed by #61
