### ISSUE TITLE
CORBA boolean type unions do not generate compilable code from idlj

### ISSUE THREAD

**Issue by hdreihah** [eclipse-ee4j/orb#64]
This bug has been reported on JDK some time ago:
http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4504275 

The java code generated from an idl union where the switch is the boolean type
will not compile with javac.  The following example IDL will compile java code
with idlj, but when we run the java code through javac it fails with syntax
errors.
--- example IDL follows --------------
module xyz
{
        union LongTypeOpt switch (boolean) {
                case TRUE: long value;
        };

};

A fix is available for JDK:
https://www.programcreek.com/java-api-examples/?code=jboss/openjdk-orb/openjdk-orb-master/src/share/classes/com/sun/tools/corba/se/idl/toJavaPortable/UnionGen.java

look at:
private void writeVerifyDefault()
{
	...
	if (Util.javaName(utype).equals ("boolean")) {
		...
	}
	...
}

**Comment by hdreihah** [comment]
The link below shows the fix (1.14 - 1.26)
http://hg.openjdk.java.net/jdk7u/jdk7u/corba/rev/583e454e0813

**Comment by Sat-Ing** [comment]
The generated code is compile clean now for me. Although there remains a problem within the read method of the helper class. If the boolean discriminator is false, then a BAD_OPERATION exception is thrown. But instead, the value should be set to a default value. Otherwise, this IDL definition would be meaningless if the discriminator always needs to be true?

**Comment by hdreihah** [comment]
Different bug. Look at:
https://bugs.openjdk.java.net/browse/JDK-8011986

**Comment by Sat-Ing** [comment]
Thanks referencing the relevant bug!
I opened this new ticket: https://github.com/eclipse-ee4j/orb/issues/118

**Comment by pzygielo** [comment]
Closing for the statement in https://github.com/eclipse-ee4j/orb/issues/64#issuecomment-760714454
