### ISSUE TITLE
Can support com.sun.jndi.cosnaming.CNCtxFactory?

### ISSUE THREAD

**Issue by kazuki43zoo** [eclipse-ee4j/orb#65]
I want to use the `com.sun.jndi.cosnaming.CNCtxFactory` on JDK 11+.

**Comment by avl42** [comment]
classes in "com.sun.*" never were public API in Java.
Anyway, I don't see how this is Lanterna-related.

**Comment by smillidge** [comment]
See #94 this brings in the COSNaming although a couple of packages change in the donation of the code by Oracle
