### ISSUE TITLE
Would it be possible to publish orb's rmic as an osgi module?

### ISSUE THREAD

**Issue by hs536** [eclipse-ee4j/orb#73]
GlassFish is looking for an alternative rmic due to the removal of tools.jar from Java 11 by JEP 220*.
*) https://openjdk.java.net/jeps/220

It appears that orb has its own rmic implementation, would it be possible to publish that as an osgi module?

If possible, I have already verified that GlassFish can reference orb's rmic by making the following modifications to orb and GlassFish:

orb side:       https://github.com/hs536/orb/commit/f78d5e548034b555b46f707149b4168e6ca68c92
GlassFish side: https://github.com/hs536/glassfish/commit/6da9614c096ab45aec52c0c195b73225ede41151

**Comment by smillidge** [comment]
@hs536 can you make a PR?
