### ISSUE TITLE
Consume library via Maven / Maven Tycho build

### ISSUE THREAD

**Issue by vogella** [eclipse-ee4j/orb#81]
Hello,

Is the corba library published to Maven or to a p2 update site? I would like to consume org.omg.CORBA in my Tycho build after moving from Java 8 to Java 11.
Best regards, Lars

**Comment by russgold** [comment]
Yes, it is in Maven central. Look for org.glassfish.corba:glassfish-corba-omgapi:4.2.0

**Comment by vogella** [comment]
Thanks

On Tue, Mar 31, 2020 at 3:28 AM Russell Gold <notifications@github.com> wrote:
>
> Yes, it is in Maven central. Look for org.glassfish.corba:glassfish-corba-omgapi:4.2.0
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Eclipse Platform project co-lead
CEO vogella GmbH

Haindaalwisch 17a, 22395 Hamburg
Amtsgericht Hamburg: HRB 127058
Geschäftsführer: Lars Vogel, Jennifer Nerlich de Vogel
USt-IdNr.: DE284122352
Fax (040) 5247 6322, Email: lars.vogel@vogella.com, Web: http://www.vogella.com
